import { useState, useRef, useEffect } from 'react'
import {
  Upload,
  X,
  Loader2,
  AlertCircle,
  CheckCircle2,
  Image as ImageIcon,
  Film,
  Sparkles,
  Lock,
  Globe,
  MessageSquare,
  Share2,
  Calendar,
  Tag,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  Play
} from 'lucide-react'
import { videoApi } from '../../services/videoApi'
import { cacheService } from '../../services/cacheService'
import { useNotifications } from '../../contexts/NotificationContext'
import { useTheme } from '../../contexts/ThemeContext'
import { VideoEditor } from './VideoEditor'

interface VideoFilters {
  brightness: number
  contrast: number
  saturate: number
  grayscale: number
  sepia: number
  hueRotate: number
  blur: number
}

interface UploadVideoProps {
  isOpen?: boolean
  onClose?: () => void
  initialVideoData?: { videoFile: File; videoUrl: string; thumbnail: string }
  onSuccess?: () => void
}

type UploadStep = 'select' | 'details' | 'options' | 'review' | 'uploading' | 'processing' | 'success' | 'error'

const CATEGORIES = [
  'Technologie & IA',
  'Business & Finance',
  'Design & UI/UX',
  'Santé & Télémédecine',
  'Droit & Fiscalité',
  'Marketing & Vente',
  'Ingénierie & Architecture',
  'Éducation & Formation',
  'Autre'
]

export const UploadVideo = ({ isOpen = false, onClose, initialVideoData, onSuccess }: UploadVideoProps): JSX.Element => {
  const { showSuccess, showError } = useNotifications()
  const { resolvedTheme } = useTheme()
  const isDark = resolvedTheme === 'dark'

  const [currentStep, setCurrentStep] = useState<UploadStep>('select')

  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [category, setCategory] = useState(CATEGORIES[0])
  const [tags, setTags] = useState('')
  const [visibility, setVisibility] = useState<'public' | 'private' | 'unlisted'>('public')

  const [allowComments, setAllowComments] = useState(true)
  const [allowAnonymousComments, setAllowAnonymousComments] = useState(false)
  const [allowSharing, setAllowSharing] = useState(true)
  const [isScheduled, setIsScheduled] = useState(false)
  const [scheduledDate, setScheduledDate] = useState('')

  const [videoFile, setVideoFile] = useState<File | null>(null)
  const [videoUrl, setVideoUrl] = useState<string>('')
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null)
  const [thumbnailPreviewUrl, setThumbnailPreviewUrl] = useState<string>('')
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<string>('')

  const [uploadProgress, setUploadProgress] = useState(0)
  const [isUploading, setIsUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const [showVideoEditor, setShowVideoEditor] = useState(false)
  const [, setVideoFilters] = useState<VideoFilters>({
    brightness: 100,
    contrast: 100,
    saturate: 100,
    grayscale: 0,
    sepia: 0,
    hueRotate: 0,
    blur: 0
  })

  const videoInputRef = useRef<HTMLInputElement>(null)
  const thumbnailInputRef = useRef<HTMLInputElement>(null)

  const MAX_FILE_SIZE = 2 * 1024 * 1024 * 1024
  const ALLOWED_VIDEO_TYPES = ['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm']
  const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp']

  useEffect(() => {
    if (!initialVideoData) return
    setVideoFile(initialVideoData.videoFile)
    setVideoUrl(initialVideoData.videoUrl)
    if (initialVideoData.thumbnail?.startsWith('data:image')) {
      fetch(initialVideoData.thumbnail)
        .then(res => res.blob())
        .then(blob => {
          setThumbnailFile(new File([blob], 'cover.jpg', { type: blob.type || 'image/jpeg' }))
          setThumbnailPreviewUrl(initialVideoData.thumbnail)
        })
        .catch(() => undefined)
    }
    setCurrentStep('details')
  }, [initialVideoData])

  const hashtags = (description.match(/#[a-zA-Z0-9_\u00C0-\u00FF]+/g) || [])
  const hasTooManyHashtags = hashtags.length > 3

  const captureCoverFromVideo = (file: File): Promise<{ file: File; dataUrl: string } | null> =>
    new Promise((resolve) => {
      const objectUrl = URL.createObjectURL(file)
      const videoEl = document.createElement('video')
      videoEl.preload = 'metadata'
      videoEl.muted = true
      videoEl.playsInline = true

      const cleanup = () => URL.revokeObjectURL(objectUrl)
      const fail = () => { cleanup(); resolve(null) }

      videoEl.onloadeddata = () => {
        videoEl.currentTime = Math.min(1, (videoEl.duration || 2) / 2)
      }

      videoEl.onseeked = () => {
        try {
          const canvas = document.createElement('canvas')
          canvas.width = videoEl.videoWidth || 640
          canvas.height = videoEl.videoHeight || 360
          const ctx = canvas.getContext('2d')
          if (!ctx) { fail(); return }
          ctx.drawImage(videoEl, 0, 0, canvas.width, canvas.height)
          const dataUrl = canvas.toDataURL('image/jpeg', 0.85)
          canvas.toBlob((blob) => {
            cleanup()
            if (!blob) { resolve(null); return }
            resolve({
              file: new File([blob], 'cover_auto.jpg', { type: 'image/jpeg' }),
              dataUrl
            })
          }, 'image/jpeg', 0.85)
        } catch {
          fail()
        }
      }

      videoEl.onerror = fail
      videoEl.src = objectUrl
    })

  const handleVideoSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    if (file.size > MAX_FILE_SIZE) {
      setError('La vidéo ne doit pas dépasser 2GB')
      return
    }

    if (!ALLOWED_VIDEO_TYPES.includes(file.type)) {
      setError('Format non supporté. Utilisez MP4, MOV, AVI ou WebM')
      return
    }

    setVideoFile(file)
    const objUrl = URL.createObjectURL(file)
    setVideoUrl(objUrl)

    if (!title.trim()) {
      setTitle(file.name.replace(/\.[^/.]+$/, '').replace(/[-_]/g, ' '))
    }
    setError(null)

    const coverRes = await captureCoverFromVideo(file)
    if (coverRes) {
      setAutoGeneratedThumbnail(coverRes.dataUrl)
      setThumbnailPreviewUrl(coverRes.dataUrl)
      setThumbnailFile(coverRes.file)
    }

    setCurrentStep('details')
  }

  const handleThumbnailSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    if (!ALLOWED_IMAGE_TYPES.includes(file.type)) {
      setError('Format d\'image non supporté. Utilisez JPEG, PNG ou WebP')
      return
    }

    setThumbnailFile(file)
    setThumbnailPreviewUrl(URL.createObjectURL(file))
    setError(null)
  }

  const handlePublish = async () => {
    if (!videoFile) {
      setError('Veuillez sélectionner un fichier vidéo')
      setCurrentStep('select')
      return
    }
    if (!title.trim()) {
      setError('Le titre de la vidéo est requis')
      setCurrentStep('details')
      return
    }
    if (hasTooManyHashtags) {
      setError('La description ne peut pas contenir plus de 3 hashtags')
      setCurrentStep('details')
      return
    }

    setIsUploading(true)
    setError(null)
    setCurrentStep('uploading')
    setUploadProgress(15)

    try {
      let finalCover = thumbnailFile
      if (!finalCover && videoFile) {
        const auto = await captureCoverFromVideo(videoFile)
        if (auto) finalCover = auto.file
      }

      const result = await videoApi.uploadVideo(
        {
          file: videoFile,
          title: title.trim(),
          description: description.trim(),
          isPublic: visibility === 'public',
          cover: finalCover,
          category,
          tags,
          allowComments,
          allowAnonymousComments,
          allowSharing,
          scheduledAt: isScheduled ? scheduledDate : undefined
        },
        (progress) => {
          setUploadProgress(Math.max(15, Math.min(95, progress)))
        }
      )

      if (result.success) {
        setUploadProgress(100)
        setCurrentStep('processing')

        setTimeout(() => {
          setCurrentStep('success')
          showSuccess('Votre vidéo d\'expertise est maintenant publiée !')

          // Invalidation immédiate du cache feed pour affichage instantané
          cacheService.invalidate('pro:videos:feed')
          cacheService.clear('pro:videos:feed')

          try {
            const saved = localStorage.getItem('exile_videos')
            const existingVideos = saved ? JSON.parse(saved) : []
            const newVideoEntry = {
              id: String(result.data?.id || Date.now()),
              title: result.data?.title || title.trim(),
              description: result.data?.description || description.trim(),
              thumbnail: result.data?.cover_url || result.data?.cover || thumbnailPreviewUrl || autoGeneratedThumbnail,
              thumbnailUrl: result.data?.cover_url || result.data?.cover || thumbnailPreviewUrl || autoGeneratedThumbnail,
              videoUrl: result.data?.file_url || result.data?.file || videoUrl,
              category: result.data?.category || category,
              viewsCount: 0,
              likesCount: 0,
              createdAt: 'À l\'instant',
              isProcessing: false,
              author: {
                id: String(result.data?.owner || 'me'),
                name: result.data?.owner_full_name || result.data?.owner_username || 'Mon Profil Pro',
                username: result.data?.owner_username || undefined,
                avatar: result.data?.owner_avatar || localStorage.getItem('exile_cached_avatar') || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
                profession: 'Expert'
              }
            }
            localStorage.setItem('exile_videos', JSON.stringify([newVideoEntry, ...existingVideos]))
          } catch {}

          window.dispatchEvent(new CustomEvent('video-uploaded'))
          window.dispatchEvent(new CustomEvent('video-published'))
          onSuccess?.()
        }, 1200)
      } else {
        setError(result.error || 'Une erreur est survenue lors de la publication')
        setCurrentStep('error')
        showError(result.error || 'Erreur lors de la publication')
      }
    } catch {
      setError('Erreur inattendue lors du téléversement')
      setCurrentStep('error')
      showError('Erreur de connexion au serveur')
    } finally {
      setIsUploading(false)
    }
  }

  const handleReset = () => {
    setVideoFile(null)
    setVideoUrl('')
    setThumbnailFile(null)
    setThumbnailPreviewUrl('')
    setTitle('')
    setDescription('')
    setTags('')
    setError(null)
    setCurrentStep('select')
  }

  if (!isOpen) return <></>

  return (
    <>
      <div className="fixed inset-0 z-[99999] bg-black/80 md:backdrop-blur-sm flex items-end md:items-center justify-center p-0 md:p-4 overflow-y-auto">
        <div className={`w-full ${isDark ? 'bg-zinc-950 md:bg-zinc-900 border-zinc-800' : 'bg-white border-slate-200'} h-full md:h-auto md:max-h-[92vh] md:max-w-2xl md:rounded-3xl border-0 md:border shadow-2xl flex flex-col overflow-hidden animate-in fade-in duration-200`}>
          
          <div className={`p-4 border-b ${isDark ? 'border-zinc-800 bg-zinc-950 md:bg-zinc-900/90' : 'border-slate-100 bg-white/90'} backdrop-blur flex items-center justify-between flex-shrink-0`}>
            <div className="flex items-center gap-3">
              {currentStep !== 'select' && currentStep !== 'uploading' && currentStep !== 'processing' && currentStep !== 'success' && currentStep !== 'error' && (
                <button
                  onClick={() => {
                    if (currentStep === 'details') setCurrentStep('select')
                    else if (currentStep === 'options') setCurrentStep('details')
                    else if (currentStep === 'review') setCurrentStep('options')
                  }}
                  className={`p-1.5 rounded-xl transition-colors ${isDark ? 'hover:bg-zinc-800 text-zinc-300' : 'hover:bg-slate-100 text-slate-700'}`}
                >
                  <ArrowLeft className="w-5 h-5" />
                </button>
              )}
              <div className="w-9 h-9 rounded-xl bg-[#FF6B00] text-white flex items-center justify-center shadow-sm">
                <Film className="w-5 h-5" />
              </div>
              <div>
                <h2 className={`text-base sm:text-lg font-bold ${isDark ? 'text-zinc-100' : 'text-slate-900'}`}>
                  Publier une Vidéo d'Expertise
                </h2>
                <p className={`text-[11px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
                  {currentStep === 'select' && 'Étape 1 sur 4 : Sélection'}
                  {currentStep === 'details' && 'Étape 2 sur 4 : Informations'}
                  {currentStep === 'options' && 'Étape 3 sur 4 : Options'}
                  {currentStep === 'review' && 'Étape 4 sur 4 : Vérification & Publication'}
                  {(currentStep === 'uploading' || currentStep === 'processing') && 'Traitement en cours...'}
                  {currentStep === 'success' && 'Vidéo publiée avec succès !'}
                  {currentStep === 'error' && 'Échec de publication'}
                </p>
              </div>
            </div>

            <button
              onClick={onClose}
              disabled={isUploading}
              className={`p-2 rounded-xl transition-colors ${isDark ? 'hover:bg-zinc-800 text-zinc-400 hover:text-white' : 'hover:bg-slate-100 text-slate-500'}`}
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {currentStep !== 'uploading' && currentStep !== 'processing' && currentStep !== 'success' && currentStep !== 'error' && (
            <div className="w-full bg-zinc-800/40 h-1">
              <div
                className="bg-[#FF6B00] h-1 transition-all duration-300"
                style={{
                  width: currentStep === 'select' ? '25%' : currentStep === 'details' ? '50%' : currentStep === 'options' ? '75%' : '100%'
                }}
              />
            </div>
          )}

          {error && (
            <div className="m-4 p-3 bg-red-500/10 border border-red-500/20 rounded-2xl flex items-center gap-3 text-red-500 text-xs font-semibold">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <p className="flex-1">{error}</p>
            </div>
          )}

          <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5">
            
            {currentStep === 'select' && (
              <div className="space-y-4">
                <input
                  type="file"
                  ref={videoInputRef}
                  onChange={handleVideoSelect}
                  accept="video/mp4,video/quicktime,video/x-msvideo,video/webm"
                  className="hidden"
                />

                <div
                  onClick={() => videoInputRef.current?.click()}
                  className={`border-2 border-dashed rounded-3xl p-8 sm:p-12 text-center transition-all cursor-pointer ${
                    isDark
                      ? 'border-zinc-800 hover:border-[#FF6B00] bg-zinc-900/40 hover:bg-zinc-900/80'
                      : 'border-slate-300 hover:border-[#FF6B00] bg-slate-50 hover:bg-slate-100'
                  }`}
                >
                  <div className="w-16 h-16 rounded-2xl bg-[#FF6B00]/10 text-[#FF6B00] flex items-center justify-center mx-auto mb-4">
                    <Upload className="w-8 h-8" />
                  </div>
                  <h3 className="text-base font-bold mb-1">
                    Sélectionnez une vidéo depuis votre appareil
                  </h3>
                  <p className={`text-xs ${isDark ? 'text-zinc-400' : 'text-slate-500'} mb-4 max-w-sm mx-auto`}>
                    Partagez votre expertise, tutoriel, étude de cas ou masterclass
                  </p>
                  <button
                    type="button"
                    className="px-5 py-2.5 bg-[#FF6B00] hover:bg-[#e05e00] text-white rounded-xl text-xs font-bold shadow-md transition-all active:scale-95"
                  >
                    Choisir un fichier
                  </button>
                  <p className={`text-[10px] ${isDark ? 'text-zinc-500' : 'text-slate-400'} mt-4`}>
                    Formats acceptés : MP4, MOV, AVI, WebM (Max 2 Go)
                  </p>
                </div>
              </div>
            )}

            {currentStep === 'details' && (
              <div className="space-y-4">
                {videoUrl && (
                  <div className="rounded-2xl border border-zinc-800 overflow-hidden bg-black relative">
                    <video
                      src={videoUrl}
                      controls
                      className="w-full max-h-56 object-contain"
                    />
                  </div>
                )}

                <div>
                  <label className={`block text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'} mb-1.5`}>
                    Titre de la vidéo *
                  </label>
                  <input
                    type="text"
                    required
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="Ex: 5 Conseils Clés pour Réussir sa Levée de Fonds"
                    className={`w-full px-3.5 py-2.5 rounded-2xl text-xs sm:text-sm border transition-all ${
                      isDark ? 'bg-zinc-900/80 border-zinc-800 text-zinc-100' : 'bg-slate-50 border-slate-200 text-slate-900'
                    } focus:outline-none focus:border-[#FF6B00]`}
                  />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className={`text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'}`}>
                      Description & Hashtags
                    </label>
                    <span className={`text-[11px] font-semibold ${hasTooManyHashtags ? 'text-red-500 font-bold' : isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
                      {hashtags.length}/3 hashtags
                    </span>
                  </div>
                  <textarea
                    rows={3}
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Résumez les points clés de votre vidéo... (ex: #Tech #Business #Finance)"
                    className={`w-full px-3.5 py-2.5 rounded-2xl text-xs sm:text-sm border transition-all resize-none ${
                      hasTooManyHashtags
                        ? 'border-red-500'
                        : isDark ? 'bg-zinc-900/80 border-zinc-800 text-zinc-100' : 'bg-slate-50 border-slate-200 text-slate-900'
                    } focus:outline-none focus:border-[#FF6B00]`}
                  />
                  {hasTooManyHashtags && (
                    <p className="text-[10px] text-red-500 font-semibold mt-1">
                      ⚠️ 3 hashtags maximum autorisés pour garantir la lisibilité du feed.
                    </p>
                  )}
                </div>

                <div>
                  <label className={`block text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'} mb-1.5`}>
                    Catégorie d'expertise
                  </label>
                  <select
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    className={`w-full px-3.5 py-2.5 rounded-2xl text-xs sm:text-sm border transition-all ${
                      isDark ? 'bg-zinc-900/80 border-zinc-800 text-zinc-100' : 'bg-slate-50 border-slate-200 text-slate-900'
                    } focus:outline-none focus:border-[#FF6B00]`}
                  >
                    {CATEGORIES.map(c => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className={`block text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'} mb-1.5`}>
                    Tags / Mots-clés (séparés par des virgules)
                  </label>
                  <div className="relative">
                    <Tag className={`absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 ${isDark ? 'text-zinc-500' : 'text-slate-400'}`} />
                    <input
                      type="text"
                      value={tags}
                      onChange={(e) => setTags(e.target.value)}
                      placeholder="startup, investissement, stratégie, saas"
                      className={`w-full pl-9 pr-3.5 py-2.5 rounded-2xl text-xs sm:text-sm border transition-all ${
                        isDark ? 'bg-zinc-900/80 border-zinc-800 text-zinc-100' : 'bg-slate-50 border-slate-200 text-slate-900'
                      } focus:outline-none focus:border-[#FF6B00]`}
                    />
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'} mb-1.5`}>
                    Miniature de la vidéo
                  </label>
                  <input
                    type="file"
                    ref={thumbnailInputRef}
                    onChange={handleThumbnailSelect}
                    accept="image/jpeg,image/png,image/webp"
                    className="hidden"
                  />
                  <div className="flex items-center gap-3">
                    {thumbnailPreviewUrl ? (
                      <div className="relative w-28 aspect-video rounded-xl overflow-hidden border border-zinc-800 bg-zinc-900 flex-shrink-0">
                        <img src={thumbnailPreviewUrl} alt="Thumbnail" className="w-full h-full object-cover" />
                      </div>
                    ) : (
                      <div className="w-28 aspect-video rounded-xl bg-zinc-800 flex items-center justify-center text-zinc-500 flex-shrink-0">
                        <ImageIcon className="w-6 h-6" />
                      </div>
                    )}
                    <button
                      type="button"
                      onClick={() => thumbnailInputRef.current?.click()}
                      className={`px-3 py-2 rounded-xl text-xs font-semibold border transition-colors ${
                        isDark ? 'bg-zinc-800 border-zinc-700 hover:bg-zinc-700 text-zinc-200' : 'bg-slate-100 border-slate-200 hover:bg-slate-200 text-slate-700'
                      }`}
                    >
                      Changer l'image
                    </button>
                  </div>
                </div>

                <div>
                  <label className={`block text-xs font-bold ${isDark ? 'text-zinc-300' : 'text-slate-700'} mb-1.5`}>
                    Visibilité
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      type="button"
                      onClick={() => setVisibility('public')}
                      className={`p-3 rounded-2xl border text-left flex items-center gap-2.5 transition-all ${
                        visibility === 'public'
                          ? 'border-[#FF6B00] bg-[#FF6B00]/10 text-[#FF6B00] font-bold'
                          : isDark ? 'border-zinc-800 bg-zinc-900/60 text-zinc-400' : 'border-slate-200 bg-slate-50 text-slate-600'
                      }`}
                    >
                      <Globe className="w-4 h-4" />
                      <div>
                        <p className="text-xs font-bold">Public</p>
                        <p className="text-[10px] opacity-70">Visible par toute la communauté</p>
                      </div>
                    </button>

                    <button
                      type="button"
                      onClick={() => setVisibility('private')}
                      className={`p-3 rounded-2xl border text-left flex items-center gap-2.5 transition-all ${
                        visibility === 'private'
                          ? 'border-[#FF6B00] bg-[#FF6B00]/10 text-[#FF6B00] font-bold'
                          : isDark ? 'border-zinc-800 bg-zinc-900/60 text-zinc-400' : 'border-slate-200 bg-slate-50 text-slate-600'
                      }`}
                    >
                      <Lock className="w-4 h-4" />
                      <div>
                        <p className="text-xs font-bold">Privé</p>
                        <p className="text-[10px] opacity-70">Visible uniquement par vous</p>
                      </div>
                    </button>
                  </div>
                </div>
              </div>
            )}

            {currentStep === 'options' && (
              <div className="space-y-4">
                <div className={`p-4 rounded-2xl border space-y-3 ${isDark ? 'bg-zinc-900/60 border-zinc-800' : 'bg-slate-50 border-slate-200'}`}>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-[#FF6B00] flex items-center gap-2">
                    <MessageSquare className="w-4 h-4" />
                    Interactions & Commentaires
                  </h3>

                  <label className="flex items-center justify-between cursor-pointer pt-1">
                    <div>
                      <p className="text-xs font-bold">Autoriser les commentaires</p>
                      <p className={`text-[11px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Les membres peuvent débattre et poser des questions</p>
                    </div>
                    <input
                      type="checkbox"
                      checked={allowComments}
                      onChange={(e) => setAllowComments(e.target.checked)}
                      className="w-4 h-4 rounded text-[#FF6B00] focus:ring-[#FF6B00]"
                    />
                  </label>

                  {allowComments && (
                    <label className="flex items-center justify-between cursor-pointer pt-2 border-t border-zinc-800/60">
                      <div>
                        <p className="text-xs font-bold">Autoriser les commentaires anonymes</p>
                        <p className={`text-[11px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Permettre les retours sans afficher l'identité</p>
                      </div>
                      <input
                        type="checkbox"
                        checked={allowAnonymousComments}
                        onChange={(e) => setAllowAnonymousComments(e.target.checked)}
                        className="w-4 h-4 rounded text-[#FF6B00] focus:ring-[#FF6B00]"
                      />
                    </label>
                  )}
                </div>

                <div className={`p-4 rounded-2xl border space-y-3 ${isDark ? 'bg-zinc-900/60 border-zinc-800' : 'bg-slate-50 border-slate-200'}`}>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-[#FF6B00] flex items-center gap-2">
                    <Share2 className="w-4 h-4" />
                    Partage & Diffusion
                  </h3>

                  <label className="flex items-center justify-between cursor-pointer">
                    <div>
                      <p className="text-xs font-bold">Autoriser le partage de la vidéo</p>
                      <p className={`text-[11px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Permettre aux utilisateurs de relayer le lien de votre vidéo</p>
                    </div>
                    <input
                      type="checkbox"
                      checked={allowSharing}
                      onChange={(e) => setAllowSharing(e.target.checked)}
                      className="w-4 h-4 rounded text-[#FF6B00] focus:ring-[#FF6B00]"
                    />
                  </label>
                </div>

                <div className={`p-4 rounded-2xl border space-y-3 ${isDark ? 'bg-zinc-900/60 border-zinc-800' : 'bg-slate-50 border-slate-200'}`}>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-[#FF6B00] flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    Planification de la publication
                  </h3>

                  <label className="flex items-center justify-between cursor-pointer">
                    <div>
                      <p className="text-xs font-bold">Programmer la publication</p>
                      <p className={`text-[11px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Définir une date et heure de sortie automatique</p>
                    </div>
                    <input
                      type="checkbox"
                      checked={isScheduled}
                      onChange={(e) => setIsScheduled(e.target.checked)}
                      className="w-4 h-4 rounded text-[#FF6B00] focus:ring-[#FF6B00]"
                    />
                  </label>

                  {isScheduled && (
                    <div className="pt-2">
                      <input
                        type="datetime-local"
                        value={scheduledDate}
                        onChange={(e) => setScheduledDate(e.target.value)}
                        className={`w-full px-3.5 py-2 rounded-xl text-xs border ${
                          isDark ? 'bg-zinc-900 border-zinc-700 text-zinc-100' : 'bg-white border-slate-300'
                        } focus:outline-none focus:border-[#FF6B00]`}
                      />
                    </div>
                  )}
                </div>
              </div>
            )}

            {currentStep === 'review' && (
              <div className="space-y-4">
                <div className={`rounded-3xl border overflow-hidden p-4 space-y-3 ${isDark ? 'bg-zinc-900/80 border-zinc-800' : 'bg-slate-50 border-slate-200'}`}>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-[#FF6B00]">
                    Récapitulatif avant publication
                  </h3>

                  <div className="flex gap-3">
                    <div className="relative w-32 aspect-video rounded-xl overflow-hidden bg-black flex-shrink-0 border border-zinc-800">
                      <img src={thumbnailPreviewUrl || autoGeneratedThumbnail} alt="Aperçu" className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
                        <Play className="w-5 h-5 text-white" />
                      </div>
                    </div>
                    <div className="min-w-0 flex-1 space-y-1">
                      <h4 className="font-bold text-xs sm:text-sm line-clamp-2">{title}</h4>
                      <p className={`text-[11px] font-semibold text-[#FF6B00]`}>{category}</p>
                      <p className={`text-[10px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
                        {visibility === 'public' ? '🌍 Public' : '🔒 Privé'} • {allowComments ? 'Commentaires activés' : 'Commentaires désactivés'}
                      </p>
                    </div>
                  </div>

                  {description && (
                    <p className={`text-xs ${isDark ? 'text-zinc-300' : 'text-slate-600'} line-clamp-2 pt-2 border-t border-zinc-800/60`}>
                      {description}
                    </p>
                  )}
                </div>

                <div className={`p-4 rounded-2xl border text-center ${isDark ? 'bg-zinc-900/40 border-zinc-800 text-zinc-400' : 'bg-slate-100 border-slate-200 text-slate-600'} text-xs`}>
                  En cliquant sur <strong>Publier</strong>, votre vidéo sera téléversée, encodée et intégrée dans le fil d'actualité professionnel.
                </div>
              </div>
            )}

            {(currentStep === 'uploading' || currentStep === 'processing') && (
              <div className="py-12 text-center space-y-4">
                <div className="relative w-16 h-16 mx-auto">
                  <div className="w-16 h-16 rounded-full border-4 border-zinc-800 border-t-[#FF6B00] animate-spin" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <Film className="w-6 h-6 text-[#FF6B00]" />
                  </div>
                </div>

                <div>
                  <h3 className="text-base font-bold mb-1">
                    {currentStep === 'uploading' ? 'Téléversement en cours...' : 'Vidéo en cours de traitement...'}
                  </h3>
                  <p className={`text-xs ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
                    {currentStep === 'uploading' ? `${uploadProgress}% transféré` : 'Optimisation du format et encodage haute définition'}
                  </p>
                </div>

                <div className="w-full max-w-xs mx-auto bg-zinc-800 h-2 rounded-full overflow-hidden">
                  <div
                    className="bg-[#FF6B00] h-full transition-all duration-300"
                    style={{ width: `${currentStep === 'processing' ? 100 : uploadProgress}%` }}
                  />
                </div>

                <p className={`text-[11px] ${isDark ? 'text-zinc-500' : 'text-slate-400'} pt-2`}>
                  État : Brouillon → Téléversement → <strong>{currentStep === 'processing' ? 'Traitement' : 'Upload'}</strong> → Publiée
                </p>
              </div>
            )}

            {currentStep === 'success' && (
              <div className="py-8 text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-emerald-500/10 text-emerald-500 flex items-center justify-center mx-auto">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <h3 className="text-lg font-bold">Votre vidéo d'expertise est en ligne !</h3>
                <p className={`text-xs ${isDark ? 'text-zinc-400' : 'text-slate-500'} max-w-sm mx-auto`}>
                  Elle est désormais visible sur votre profil et dans le fil d'actualité professionnel.
                </p>

                <div className="pt-4 flex justify-center gap-3">
                  <button
                    onClick={onClose}
                    className="px-6 py-2.5 bg-[#FF6B00] text-white rounded-xl text-xs font-bold shadow-md hover:bg-[#e05e00]"
                  >
                    Voir mon fil
                  </button>
                </div>
              </div>
            )}

            {currentStep === 'error' && (
              <div className="py-8 text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-red-500/10 text-red-500 flex items-center justify-center mx-auto">
                  <AlertCircle className="w-8 h-8" />
                </div>
                <h3 className="text-lg font-bold">Échec du téléversement</h3>
                <p className={`text-xs text-red-400 max-w-sm mx-auto`}>
                  {error || 'Une interruption réseau est survenue. Veuillez réessayer.'}
                </p>

                <div className="pt-4 flex justify-center gap-3">
                  <button
                    onClick={handlePublish}
                    className="px-6 py-2.5 bg-[#FF6B00] text-white rounded-xl text-xs font-bold shadow-md hover:bg-[#e05e00] flex items-center gap-2"
                  >
                    <RefreshCw className="w-4 h-4" />
                    <span>Réessayer</span>
                  </button>
                  <button
                    onClick={handleReset}
                    className="px-4 py-2.5 bg-zinc-800 text-zinc-300 rounded-xl text-xs font-semibold hover:bg-zinc-700"
                  >
                    Recommencer
                  </button>
                </div>
              </div>
            )}

          </div>

          {currentStep !== 'uploading' && currentStep !== 'processing' && currentStep !== 'success' && currentStep !== 'error' && (
            <div className={`p-4 border-t ${isDark ? 'border-zinc-800 bg-zinc-950 md:bg-zinc-900' : 'border-slate-100 bg-white'} flex items-center justify-between gap-3 flex-shrink-0`}>
              <button
                type="button"
                onClick={onClose}
                className={`px-4 py-2.5 rounded-xl text-xs font-semibold transition-colors ${
                  isDark ? 'bg-zinc-800 hover:bg-zinc-700 text-zinc-300' : 'bg-slate-100 hover:bg-slate-200 text-slate-700'
                }`}
              >
                Annuler
              </button>

              <div className="flex items-center gap-2">
                {currentStep === 'details' && (
                  <button
                    type="button"
                    disabled={!title.trim() || hasTooManyHashtags}
                    onClick={() => setCurrentStep('options')}
                    className="px-5 py-2.5 rounded-xl bg-[#FF6B00] hover:bg-[#e05e00] text-white font-bold text-xs shadow-md transition-all active:scale-95 disabled:opacity-50 flex items-center gap-1.5"
                  >
                    <span>Suivant : Options</span>
                    <ArrowRight className="w-4 h-4" />
                  </button>
                )}

                {currentStep === 'options' && (
                  <button
                    type="button"
                    onClick={() => setCurrentStep('review')}
                    className="px-5 py-2.5 rounded-xl bg-[#FF6B00] hover:bg-[#e05e00] text-white font-bold text-xs shadow-md transition-all active:scale-95 flex items-center gap-1.5"
                  >
                    <span>Suivant : Résumé</span>
                    <ArrowRight className="w-4 h-4" />
                  </button>
                )}

                {currentStep === 'review' && (
                  <button
                    type="button"
                    onClick={handlePublish}
                    className="px-6 py-2.5 rounded-xl bg-[#FF6B00] hover:bg-[#e05e00] text-white font-bold text-xs shadow-md transition-all active:scale-95 flex items-center gap-2"
                  >
                    <Sparkles className="w-4 h-4" />
                    <span>Publier la vidéo</span>
                  </button>
                )}
              </div>
            </div>
          )}

        </div>
      </div>

      {showVideoEditor && videoFile && videoUrl && (
        <VideoEditor
          videoFile={videoFile}
          videoUrl={videoUrl}
          onApplyFilters={(filters) => {
            setVideoFilters(filters)
            setShowVideoEditor(false)
          }}
          onCancel={() => setShowVideoEditor(false)}
        />
      )}
    </>
  )
}

export default UploadVideo
